
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 13 18:24:38 COT 2021
//----------------------------------------------------

package AnalizadorLex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 41;
  public static final int Coma = 54;
  public static final int ScanF = 26;
  public static final int Llave_c = 48;
  public static final int Op_booleano = 44;
  public static final int Double = 12;
  public static final int Llave_a = 47;
  public static final int Unsigned = 20;
  public static final int If = 6;
  public static final int T_dato = 4;
  public static final int Default = 33;
  public static final int Else = 7;
  public static final int Cout = 28;
  public static final int Enum = 21;
  public static final int Break = 34;
  public static final int Corchete_c = 50;
  public static final int Corchete_a = 49;
  public static final int Extern = 22;
  public static final int Union = 17;
  public static final int Long = 16;
  public static final int Punto = 53;
  public static final int Parent_c = 46;
  public static final int Return = 57;
  public static final int Parent_a = 45;
  public static final int While = 9;
  public static final int Division = 39;
  public static final int Int = 11;
  public static final int Cadena = 5;
  public static final int Float = 14;
  public static final int For = 10;
  public static final int P_coma = 52;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Switch = 31;
  public static final int TypeDef = 24;
  public static final int Linea = 2;
  public static final int Char = 13;
  public static final int Op_atribucion = 42;
  public static final int ERROR = 58;
  public static final int Do = 8;
  public static final int Continue = 29;
  public static final int Op_logico = 40;
  public static final int Case = 32;
  public static final int Short = 19;
  public static final int Register = 23;
  public static final int GoTo = 30;
  public static final int Const = 15;
  public static final int Identificador = 55;
  public static final int Struct = 18;
  public static final int Cin = 27;
  public static final int Resta = 37;
  public static final int PrintF = 25;
  public static final int Multiplicacion = 38;
  public static final int Op_incremento = 43;
  public static final int Numero = 56;
  public static final int Suma = 36;
  public static final int Main = 51;
  public static final int Igual = 35;
  public static final int Comillas = 3;
}

